import { ipcMain, shell } from 'electron'
import * as nodemailer from 'nodemailer'
import { getPrisma } from '../database'

interface SmtpConfig {
  host: string
  port: number
  secure: boolean
  user: string
  pass: string
  from: string
}

interface SendEmailOptions {
  to: string | string[]
  subject: string
  body: string
  pdfBase64: string
  pdfFilename: string
  smtpConfig: SmtpConfig
}

function formatSmtpError(err: any): string {
  const msg = err?.message || String(err)
  if (msg.includes('535') || msg.includes('BadCredentials') || msg.includes('Username and Password not accepted')) {
    return 'Gmail Authentication Failed (535 5.7.8): Google requires a 16-character "App Password" instead of your standard Gmail account password. Please enable 2-Step Verification on your Google Account and generate an App Password under Security settings.'
  }
  if (msg.includes('wrong version number') || msg.includes('WRONG_VERSION_NUMBER') || msg.includes('SSL') || msg.includes('TLS')) {
    return 'SSL/TLS Mismatch (WRONG_VERSION_NUMBER): Port 587 requires "Use SSL/TLS" to be UNCHECKED (STARTTLS). Port 465 requires "Use SSL/TLS" to be CHECKED.'
  }
  if (msg.includes('ETIMEDOUT') || msg.includes('ESOCKETTIMEDOUT') || msg.includes('ECONNREFUSED')) {
    return `Connection Failed (${err.code || 'Network Error'}): Could not connect to SMTP server. Please verify your host and port.`
  }
  return msg
}

export function registerEmailHandlers(): void {
  const prisma = getPrisma()

  // Open a URL in the system default browser
  ipcMain.handle('shell:openExternal', async (_, url: string) => {
    await shell.openExternal(url)
  })

  // Test SMTP connection
  ipcMain.handle('email:testConnection', async (_, smtpConfig: SmtpConfig) => {
    try {
      const port = Number(smtpConfig.port) || 587
      // Port 465 uses direct SSL (secure: true). Port 587/25 uses STARTTLS (secure: false).
      const secure = port === 465 ? true : (port === 587 || port === 25 ? false : Boolean(smtpConfig.secure))

      const transporter = nodemailer.createTransport({
        host: smtpConfig.host,
        port,
        secure,
        auth: {
          user: smtpConfig.user,
          pass: smtpConfig.pass
        },
        tls: { rejectUnauthorized: false }
      })
      await transporter.verify()
      return { success: true }
    } catch (err: any) {
      return { success: false, error: formatSmtpError(err) }
    }
  })

  // Send email with PDF attachment (supports multiple recipients)
  ipcMain.handle('email:sendWithPdf', async (_, options: SendEmailOptions) => {
    try {
      const { to, subject, body, pdfBase64, pdfFilename, smtpConfig } = options

      // Normalise recipients to array
      const recipients: string[] = Array.isArray(to)
        ? to.filter(Boolean)
        : to.split(/[,;]/).map(s => s.trim()).filter(Boolean)

      if (recipients.length === 0) {
        return { success: false, error: 'No recipients specified' }
      }

      const port = Number(smtpConfig.port) || 587
      const secure = port === 465 ? true : (port === 587 || port === 25 ? false : Boolean(smtpConfig.secure))

      const transporter = nodemailer.createTransport({
        host: smtpConfig.host,
        port,
        secure,
        auth: {
          user: smtpConfig.user,
          pass: smtpConfig.pass
        },
        tls: { rejectUnauthorized: false }
      })

      const pdfBuffer = Buffer.from(pdfBase64, 'base64')

      await transporter.sendMail({
        from: smtpConfig.from || smtpConfig.user,
        to: recipients.join(', '),
        subject,
        html: `<div style="font-family: Arial, sans-serif; line-height: 1.6; color: #1f2937;">
          ${body.replace(/\n/g, '<br>')}
          <hr style="margin-top: 24px; border: none; border-top: 1px solid #e5e7eb;" />
          <p style="color: #6b7280; font-size: 12px;">
            This report was generated by <strong>Project Workspace Manager</strong>.<br/>
            The full project summary PDF is attached.
          </p>
        </div>`,
        attachments: [
          {
            filename: pdfFilename,
            content: pdfBuffer,
            contentType: 'application/pdf'
          }
        ]
      })

      return { success: true }
    } catch (err: any) {
      console.error('[Email] Send failed:', err)
      return { success: false, error: formatSmtpError(err) }
    }
  })

  // Get saved SMTP config from settings (legacy single-config, kept for backward compat)
  ipcMain.handle('email:getSmtpConfig', async () => {
    const keys = ['smtp_host', 'smtp_port', 'smtp_secure', 'smtp_user', 'smtp_from']
    const settings = await prisma.setting.findMany({ where: { key: { in: keys } } })
    const map: Record<string, string> = {}
    for (const s of settings) map[s.key] = s.value
    return {
      host: map['smtp_host'] || '',
      port: parseInt(map['smtp_port'] || '587'),
      secure: map['smtp_secure'] === 'true',
      user: map['smtp_user'] || '',
      from: map['smtp_from'] || ''
    }
  })

  // ─── SMTP Profile CRUD ────────────────────────────────────────────────────────

  // Get all saved profiles (password excluded from list for security)
  ipcMain.handle('email:getProfiles', async () => {
    const profiles = await prisma.smtpProfile.findMany({
      select: { id: true, name: true, host: true, port: true, secure: true, user: true, from: true, createdAt: true },
      orderBy: { createdAt: 'asc' }
    })
    return profiles
  })

  // Save (create or update) a profile — pass is only updated if provided
  ipcMain.handle('email:saveProfile', async (_, profile: {
    id?: string
    name: string
    host: string
    port: number
    secure: boolean
    user: string
    pass?: string
    from: string
  }) => {
    try {
      if (profile.id) {
        // Update existing — only update pass if a new one was provided
        const updateData: any = {
          name: profile.name,
          host: profile.host,
          port: profile.port,
          secure: profile.secure,
          user: profile.user,
          from: profile.from
        }
        if (profile.pass && profile.pass.trim()) {
          updateData.pass = profile.pass
        }
        const updated = await prisma.smtpProfile.update({
          where: { id: profile.id },
          data: updateData
        })
        return { success: true, profile: updated }
      } else {
        // Create new
        const created = await prisma.smtpProfile.create({
          data: {
            name: profile.name,
            host: profile.host,
            port: profile.port,
            secure: profile.secure,
            user: profile.user,
            pass: profile.pass || '',
            from: profile.from
          }
        })
        return { success: true, profile: created }
      }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Delete a profile by id
  ipcMain.handle('email:deleteProfile', async (_, id: string) => {
    try {
      await prisma.smtpProfile.delete({ where: { id } })
      return { success: true }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Get the password for a specific profile (fetched on demand, not in list)
  ipcMain.handle('email:getProfilePass', async (_, id: string) => {
    try {
      const profile = await prisma.smtpProfile.findUnique({ where: { id }, select: { pass: true } })
      return { success: true, pass: profile?.pass || '' }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })
}
