import { ipcMain, shell } from 'electron'
import * as nodemailer from 'nodemailer'
import { getPrisma } from '../database'

interface SmtpConfig {
  host: string
  port: number
  secure: boolean
  user: string
  pass: string
  from: string
}

interface SendEmailOptions {
  to: string | string[]
  cc?: string | string[]
  subject: string
  body: string
  pdfBase64: string
  pdfFilename: string
  smtpConfig: SmtpConfig
}

function formatSmtpError(err: any): string {
  const msg = err?.message || String(err)
  if (msg.includes('535') || msg.includes('BadCredentials') || msg.includes('Username and Password not accepted')) {
    return 'Gmail Authentication Failed (535 5.7.8): Google requires a 16-character "App Password" instead of your standard Gmail account password. Please enable 2-Step Verification on your Google Account and generate an App Password under Security settings.'
  }
  if (msg.includes('wrong version number') || msg.includes('WRONG_VERSION_NUMBER') || msg.includes('SSL') || msg.includes('TLS')) {
    return 'SSL/TLS Mismatch (WRONG_VERSION_NUMBER): Port 587 requires "Use SSL/TLS" to be UNCHECKED (STARTTLS). Port 465 requires "Use SSL/TLS" to be CHECKED.'
  }
  if (msg.includes('ETIMEDOUT') || msg.includes('ESOCKETTIMEDOUT') || msg.includes('ECONNREFUSED')) {
    return `Connection Failed (${err.code || 'Network Error'}): Could not connect to SMTP server. Please verify your host and port.`
  }
  return msg
}

export function registerEmailHandlers(): void {
  const prisma = getPrisma()

  // Open a URL in the system default browser
  ipcMain.handle('shell:openExternal', async (_, url: string) => {
    await shell.openExternal(url)
  })

  // Test SMTP connection
  ipcMain.handle('email:testConnection', async (_, smtpConfig: SmtpConfig) => {
    try {
      const port = Number(smtpConfig.port) || 587
      // Port 465 uses direct SSL (secure: true). Port 587/25 uses STARTTLS (secure: false).
      const secure = port === 465 ? true : (port === 587 || port === 25 ? false : Boolean(smtpConfig.secure))

      const transporter = nodemailer.createTransport({
        host: smtpConfig.host,
        port,
        secure,
        auth: {
          user: smtpConfig.user,
          pass: smtpConfig.pass
        },
        tls: { rejectUnauthorized: false }
      })
      await transporter.verify()
      return { success: true }
    } catch (err: any) {
      return { success: false, error: formatSmtpError(err) }
    }
  })

  // Send email with PDF attachment (supports multiple recipients & CC)
  ipcMain.handle('email:sendWithPdf', async (_, options: SendEmailOptions) => {
    try {
      const { to, cc, subject, body, pdfBase64, pdfFilename, smtpConfig } = options

      // Normalise recipients to array
      const recipients: string[] = Array.isArray(to)
        ? to.filter(Boolean)
        : to.split(/[,;]/).map(s => s.trim()).filter(Boolean)

      if (recipients.length === 0) {
        return { success: false, error: 'No recipients specified' }
      }

      const ccRecipients: string[] = cc
        ? (Array.isArray(cc) ? cc.filter(Boolean) : cc.split(/[,;]/).map(s => s.trim()).filter(Boolean))
        : []

      const port = Number(smtpConfig.port) || 587
      const secure = port === 465 ? true : (port === 587 || port === 25 ? false : Boolean(smtpConfig.secure))

      const transporter = nodemailer.createTransport({
        host: smtpConfig.host,
        port,
        secure,
        auth: {
          user: smtpConfig.user,
          pass: smtpConfig.pass
        },
        tls: { rejectUnauthorized: false }
      })

      const pdfBuffer = Buffer.from(pdfBase64, 'base64')

      await transporter.sendMail({
        from: smtpConfig.from || smtpConfig.user,
        to: recipients.join(', '),
        ...(ccRecipients.length > 0 ? { cc: ccRecipients.join(', ') } : {}),
        subject,
        html: `<div style="font-family: Arial, sans-serif; line-height: 1.6; color: #1f2937;">
          ${body.replace(/\n/g, '<br>')}
          <hr style="margin-top: 24px; border: none; border-top: 1px solid #e5e7eb;" />
          <p style="color: #6b7280; font-size: 12px;">
            This report was generated by <strong>Project Workspace Manager</strong>.<br/>
            The full project summary PDF is attached.
          </p>
        </div>`,
        attachments: [
          {
            filename: pdfFilename,
            content: pdfBuffer,
            contentType: 'application/pdf'
          }
        ]
      })

      return { success: true }
    } catch (err: any) {
      console.error('[Email] Send failed:', err)
      return { success: false, error: formatSmtpError(err) }
    }
  })

  // Get saved SMTP config from settings (legacy single-config, kept for backward compat)
  ipcMain.handle('email:getSmtpConfig', async () => {
    const keys = ['smtp_host', 'smtp_port', 'smtp_secure', 'smtp_user', 'smtp_from']
    const settings = await prisma.setting.findMany({ where: { key: { in: keys } } })
    const map: Record<string, string> = {}
    for (const s of settings) map[s.key] = s.value
    return {
      host: map['smtp_host'] || '',
      port: parseInt(map['smtp_port'] || '587'),
      secure: map['smtp_secure'] === 'true',
      user: map['smtp_user'] || '',
      from: map['smtp_from'] || ''
    }
  })

  // ─── SMTP Profile CRUD ────────────────────────────────────────────────────────

  // Get all saved profiles (password excluded from list for security)
  ipcMain.handle('email:getProfiles', async () => {
    const profiles = await prisma.smtpProfile.findMany({
      select: { id: true, name: true, host: true, port: true, secure: true, user: true, from: true, createdAt: true },
      orderBy: { createdAt: 'asc' }
    })
    return profiles
  })

  // Save (create or update) a profile — pass is only updated if provided
  ipcMain.handle('email:saveProfile', async (_, profile: {
    id?: string
    name: string
    host: string
    port: number
    secure: boolean
    user: string
    pass?: string
    from: string
  }) => {
    try {
      if (profile.id) {
        // Update existing — only update pass if a new one was provided
        const updateData: any = {
          name: profile.name,
          host: profile.host,
          port: profile.port,
          secure: profile.secure,
          user: profile.user,
          from: profile.from
        }
        if (profile.pass && profile.pass.trim()) {
          updateData.pass = profile.pass
        }
        const updated = await prisma.smtpProfile.update({
          where: { id: profile.id },
          data: updateData
        })
        return { success: true, profile: updated }
      } else {
        // Create new
        const created = await prisma.smtpProfile.create({
          data: {
            name: profile.name,
            host: profile.host,
            port: profile.port,
            secure: profile.secure,
            user: profile.user,
            pass: profile.pass || '',
            from: profile.from
          }
        })
        return { success: true, profile: created }
      }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Delete a profile by id
  ipcMain.handle('email:deleteProfile', async (_, id: string) => {
    try {
      await prisma.smtpProfile.delete({ where: { id } })
      return { success: true }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Get the password for a specific profile (fetched on demand, not in list)
  ipcMain.handle('email:getProfilePass', async (_, id: string) => {
    try {
      const profile = await prisma.smtpProfile.findUnique({ where: { id }, select: { pass: true } })
      return { success: true, pass: profile?.pass || '' }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // ─── EMAIL TEMPLATES IPC HANDLERS ──────────────────────────────────────────────

  const DEFAULT_EMAIL_TEMPLATES = [
    {
      id: 'tpl-1',
      name: 'Professional Invoice Notification',
      category: 'Billing / Invoice',
      subject: 'Invoice {{invoice_number}} from {{company_name}}',
      body: 'Hello {{client_name}},\n\nPlease find attached invoice {{invoice_number}} for your review.\n\nTotal Amount: {{amount}}\nDue Date: {{due_date}}\n\nPlease let us know if you have any questions.\n\nBest regards,\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-2',
      name: 'Friendly Payment Reminder',
      category: 'Payment Reminder',
      subject: 'Friendly Reminder: Invoice {{invoice_number}} Due Soon',
      body: 'Dear {{client_name}},\n\nThis is a gentle reminder that payment for invoice {{invoice_number}} ({{amount}}) is due on {{due_date}}.\n\nIf you have already sent payment, please disregard this notice.\n\nThank you for your business!\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-3',
      name: 'Urgent Overdue Notice',
      category: 'Overdue Notice',
      subject: 'URGENT: Invoice {{invoice_number}} is Past Due',
      body: 'Dear {{client_name}},\n\nOur records show that invoice {{invoice_number}} for {{amount}}, which was due on {{due_date}}, remains unpaid.\n\nPlease arrange for payment as soon as possible to avoid any service disruptions.\n\nThank you,\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-4',
      name: 'Payment Confirmation & Thank You',
      category: 'Payment Receipt',
      subject: 'Payment Received - Thank You! (Invoice {{invoice_number}})',
      body: 'Dear {{client_name}},\n\nWe have received your payment for invoice {{invoice_number}} ({{amount}}). Thank you very much!\n\nWe appreciate working with you.\n\nBest regards,\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-5',
      name: 'Project Proposal & Scope Delivery',
      category: 'Proposal / Quote',
      subject: 'Project Proposal & Scope for {{project_name}}',
      body: 'Hello {{client_name}},\n\nThank you for considering {{company_name}} for your project.\n\nPlease find attached our detailed proposal and estimated scope for {{project_name}}.\n\nWe look forward to collaborating with you!\n\nWarm regards,\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-6',
      name: 'Weekly Project Progress Update',
      category: 'Progress Update',
      subject: 'Weekly Progress Update: {{project_name}}',
      body: 'Hello {{client_name}},\n\nHere is our weekly update on {{project_name}}.\n\nWe have made great progress on key deliverables this week and remain on schedule.\n\nPlease review the attached summary report.\n\nBest,\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-7',
      name: 'Milestone Completion Notice',
      category: 'Milestone',
      subject: 'Milestone Completed for {{project_name}}',
      body: 'Dear {{client_name}},\n\nWe are pleased to inform you that we have successfully completed the latest milestone for {{project_name}}.\n\nPlease review the details in the attached document.\n\nThank you,\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-8',
      name: 'Final Deliverables Handover',
      category: 'Deliverables',
      subject: 'Final Deliverables Handover: {{project_name}}',
      body: 'Dear {{client_name}},\n\nWe are excited to share that all deliverables for {{project_name}} have been completed and finalized.\n\nAttached is the final report and asset checklist for your records.\n\nThank you for choosing {{company_name}}!\n\nBest regards,\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-9',
      name: 'Formal Business Cover Letter',
      category: 'Formal Correspondence',
      subject: 'Formal Notice Regarding {{project_name}}',
      body: 'To {{client_name}},\n\nPlease accept the attached documentation regarding {{project_name}}.\n\nShould you require further information or formal verification, please feel free to reach out directly.\n\nSincerely,\n{{company_name}}',
      isPrebuilt: true
    },
    {
      id: 'tpl-10',
      name: 'Client Onboarding & Welcome',
      category: 'Onboarding',
      subject: 'Welcome to {{company_name}} - Project Kickoff for {{project_name}}',
      body: 'Dear {{client_name}},\n\nWelcome to {{company_name}}! We are thrilled to start working on {{project_name}} with you.\n\nPlease find attached our onboarding overview and next steps.\n\nWarm regards,\n{{company_name}}',
      isPrebuilt: true
    }
  ]

  // Get all email templates (merges prebuilts & custom templates)
  ipcMain.handle('email:getTemplates', async () => {
    try {
      const setting = await prisma.setting.findUnique({ where: { key: 'email_templates' } })
      let templates = setting?.value ? JSON.parse(setting.value) : []
      if (!templates || templates.length === 0) {
        templates = DEFAULT_EMAIL_TEMPLATES
        await prisma.setting.upsert({
          where: { key: 'email_templates' },
          update: { value: JSON.stringify(templates) },
          create: { key: 'email_templates', value: JSON.stringify(templates) }
        })
      }
      return templates
    } catch (err: any) {
      console.error('[Email] Failed to load templates:', err)
      return DEFAULT_EMAIL_TEMPLATES
    }
  })

  // Save email template (create or update)
  ipcMain.handle('email:saveTemplate', async (_, template: any) => {
    try {
      const setting = await prisma.setting.findUnique({ where: { key: 'email_templates' } })
      let templates: any[] = setting?.value ? JSON.parse(setting.value) : [...DEFAULT_EMAIL_TEMPLATES]
      if (template.id) {
        const index = templates.findIndex(t => t.id === template.id)
        if (index >= 0) {
          templates[index] = { ...templates[index], ...template }
        } else {
          templates.push(template)
        }
      } else {
        const newTpl = {
          ...template,
          id: `custom-${Date.now()}`,
          isPrebuilt: false
        }
        templates.push(newTpl)
      }
      await prisma.setting.upsert({
        where: { key: 'email_templates' },
        update: { value: JSON.stringify(templates) },
        create: { key: 'email_templates', value: JSON.stringify(templates) }
      })
      return { success: true, templates }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Delete an email template
  ipcMain.handle('email:deleteTemplate', async (_, id: string) => {
    try {
      const setting = await prisma.setting.findUnique({ where: { key: 'email_templates' } })
      let templates: any[] = setting?.value ? JSON.parse(setting.value) : [...DEFAULT_EMAIL_TEMPLATES]
      templates = templates.filter(t => t.id !== id)
      await prisma.setting.upsert({
        where: { key: 'email_templates' },
        update: { value: JSON.stringify(templates) },
        create: { key: 'email_templates', value: JSON.stringify(templates) }
      })
      return { success: true, templates }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Reset to default 10 prebuilt templates
  ipcMain.handle('email:resetDefaultTemplates', async () => {
    try {
      await prisma.setting.upsert({
        where: { key: 'email_templates' },
        update: { value: JSON.stringify(DEFAULT_EMAIL_TEMPLATES) },
        create: { key: 'email_templates', value: JSON.stringify(DEFAULT_EMAIL_TEMPLATES) }
      })
      return { success: true, templates: DEFAULT_EMAIL_TEMPLATES }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Get SMTP Profile -> Template Mappings (which email account uses what template)
  ipcMain.handle('email:getProfileTemplateMappings', async () => {
    try {
      const setting = await prisma.setting.findUnique({ where: { key: 'email_profile_template_mappings' } })
      return setting?.value ? JSON.parse(setting.value) : {}
    } catch (err) {
      return {}
    }
  })

  // Set SMTP Profile -> Template Mapping
  ipcMain.handle('email:setProfileTemplateMapping', async (_, { profileId, templateId }: { profileId: string; templateId: string }) => {
    try {
      const setting = await prisma.setting.findUnique({ where: { key: 'email_profile_template_mappings' } })
      const mappings: Record<string, string> = setting?.value ? JSON.parse(setting.value) : {}
      if (templateId) {
        mappings[profileId] = templateId
      } else {
        delete mappings[profileId]
      }
      await prisma.setting.upsert({
        where: { key: 'email_profile_template_mappings' },
        update: { value: JSON.stringify(mappings) },
        create: { key: 'email_profile_template_mappings', value: JSON.stringify(mappings) }
      })
      return { success: true, mappings }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Store profile connection status result
  ipcMain.handle('email:setProfileStatus', async (_, { profileId, isConnected, lastError }: { profileId: string; isConnected: boolean; lastError?: string }) => {
    try {
      const setting = await prisma.setting.findUnique({ where: { key: 'email_profile_statuses' } })
      const statuses: Record<string, { isConnected: boolean; lastError?: string; checkedAt: string }> = setting?.value ? JSON.parse(setting.value) : {}
      statuses[profileId] = { isConnected, lastError, checkedAt: new Date().toISOString() }
      await prisma.setting.upsert({
        where: { key: 'email_profile_statuses' },
        update: { value: JSON.stringify(statuses) },
        create: { key: 'email_profile_statuses', value: JSON.stringify(statuses) }
      })
      return { success: true, statuses }
    } catch (err: any) {
      return { success: false, error: err.message }
    }
  })

  // Get profile connection statuses
  ipcMain.handle('email:getProfileStatuses', async () => {
    try {
      const setting = await prisma.setting.findUnique({ where: { key: 'email_profile_statuses' } })
      return setting?.value ? JSON.parse(setting.value) : {}
    } catch (err) {
      return {}
    }
  })
}
